package com.yshop.service.product.dao;

import com.yshop.service.product.dao.model.ProductParam;
import com.yshop.service.product.dao.model.ProductParamExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductParamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_param
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    int countByExample(ProductParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_param
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    int deleteByExample(ProductParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_param
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_param
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    int insert(ProductParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_param
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    int insertSelective(ProductParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_param
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    List<ProductParam> selectByExampleWithBLOBs(ProductParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_param
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    List<ProductParam> selectByExample(ProductParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_param
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    ProductParam selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_param
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    int updateByExampleSelective(@Param("record") ProductParam record, @Param("example") ProductParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_param
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") ProductParam record, @Param("example") ProductParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_param
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    int updateByExample(@Param("record") ProductParam record, @Param("example") ProductParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_param
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    int updateByPrimaryKeySelective(ProductParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_param
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(ProductParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_param
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    int updateByPrimaryKey(ProductParam record);
}