package com.yshop.service.product.dao.model;

import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_id
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.status
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.user_id
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.payment_amount
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    private Long paymentAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.payment_type
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    private Byte paymentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.payment_time
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    private Date paymentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.post_fee
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    private Long postFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.consign_time
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    private Date consignTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.shipping_name
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    private String shippingName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.shipping_code
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    private String shippingCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.buyer_message
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    private String buyerMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.buyer_nick
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    private String buyerNick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.buyer_rate
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    private Integer buyerRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.ctime
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.mtime
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    private Date mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.is_delete
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    private Byte isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_id
     *
     * @return the value of order.order_id
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_id
     *
     * @param orderId the value for order.order_id
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.status
     *
     * @return the value of order.status
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.status
     *
     * @param status the value for order.status
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.user_id
     *
     * @return the value of order.user_id
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.user_id
     *
     * @param userId the value for order.user_id
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.payment_amount
     *
     * @return the value of order.payment_amount
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public Long getPaymentAmount() {
        return paymentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.payment_amount
     *
     * @param paymentAmount the value for order.payment_amount
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public void setPaymentAmount(Long paymentAmount) {
        this.paymentAmount = paymentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.payment_type
     *
     * @return the value of order.payment_type
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public Byte getPaymentType() {
        return paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.payment_type
     *
     * @param paymentType the value for order.payment_type
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public void setPaymentType(Byte paymentType) {
        this.paymentType = paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.payment_time
     *
     * @return the value of order.payment_time
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public Date getPaymentTime() {
        return paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.payment_time
     *
     * @param paymentTime the value for order.payment_time
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public void setPaymentTime(Date paymentTime) {
        this.paymentTime = paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.post_fee
     *
     * @return the value of order.post_fee
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public Long getPostFee() {
        return postFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.post_fee
     *
     * @param postFee the value for order.post_fee
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public void setPostFee(Long postFee) {
        this.postFee = postFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.consign_time
     *
     * @return the value of order.consign_time
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public Date getConsignTime() {
        return consignTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.consign_time
     *
     * @param consignTime the value for order.consign_time
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public void setConsignTime(Date consignTime) {
        this.consignTime = consignTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.shipping_name
     *
     * @return the value of order.shipping_name
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public String getShippingName() {
        return shippingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.shipping_name
     *
     * @param shippingName the value for order.shipping_name
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public void setShippingName(String shippingName) {
        this.shippingName = shippingName == null ? null : shippingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.shipping_code
     *
     * @return the value of order.shipping_code
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public String getShippingCode() {
        return shippingCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.shipping_code
     *
     * @param shippingCode the value for order.shipping_code
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public void setShippingCode(String shippingCode) {
        this.shippingCode = shippingCode == null ? null : shippingCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.buyer_message
     *
     * @return the value of order.buyer_message
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public String getBuyerMessage() {
        return buyerMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.buyer_message
     *
     * @param buyerMessage the value for order.buyer_message
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public void setBuyerMessage(String buyerMessage) {
        this.buyerMessage = buyerMessage == null ? null : buyerMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.buyer_nick
     *
     * @return the value of order.buyer_nick
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public String getBuyerNick() {
        return buyerNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.buyer_nick
     *
     * @param buyerNick the value for order.buyer_nick
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public void setBuyerNick(String buyerNick) {
        this.buyerNick = buyerNick == null ? null : buyerNick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.buyer_rate
     *
     * @return the value of order.buyer_rate
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public Integer getBuyerRate() {
        return buyerRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.buyer_rate
     *
     * @param buyerRate the value for order.buyer_rate
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public void setBuyerRate(Integer buyerRate) {
        this.buyerRate = buyerRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.ctime
     *
     * @return the value of order.ctime
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.ctime
     *
     * @param ctime the value for order.ctime
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.mtime
     *
     * @return the value of order.mtime
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.mtime
     *
     * @param mtime the value for order.mtime
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.is_delete
     *
     * @return the value of order.is_delete
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.is_delete
     *
     * @param isDelete the value for order.is_delete
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }
}