package com.yshop.service.product.dao.model;

import java.util.Date;

public class ProductParamMapping {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_param_mapping.id
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_param_mapping.product_id
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_param_mapping.ctime
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_param_mapping.mtime
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    private Date mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_param_mapping.is_delete
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    private Byte isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_param_mapping.param_data
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    private String paramData;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_param_mapping.id
     *
     * @return the value of product_param_mapping.id
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_param_mapping.id
     *
     * @param id the value for product_param_mapping.id
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_param_mapping.product_id
     *
     * @return the value of product_param_mapping.product_id
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_param_mapping.product_id
     *
     * @param productId the value for product_param_mapping.product_id
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_param_mapping.ctime
     *
     * @return the value of product_param_mapping.ctime
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_param_mapping.ctime
     *
     * @param ctime the value for product_param_mapping.ctime
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_param_mapping.mtime
     *
     * @return the value of product_param_mapping.mtime
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_param_mapping.mtime
     *
     * @param mtime the value for product_param_mapping.mtime
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_param_mapping.is_delete
     *
     * @return the value of product_param_mapping.is_delete
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_param_mapping.is_delete
     *
     * @param isDelete the value for product_param_mapping.is_delete
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_param_mapping.param_data
     *
     * @return the value of product_param_mapping.param_data
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public String getParamData() {
        return paramData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_param_mapping.param_data
     *
     * @param paramData the value for product_param_mapping.param_data
     *
     * @mbggenerated Sun Apr 15 23:38:02 CST 2018
     */
    public void setParamData(String paramData) {
        this.paramData = paramData == null ? null : paramData.trim();
    }
}